# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Program Files\Python 2.7\Bulk_Renamer\V1.1\Bulk renamer code V1.101\V1.2\BulkRename7B.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Renamer(object):
    def setupUi(self, Renamer):
        Renamer.setObjectName(_fromUtf8("Renamer"))
        Renamer.resize(807, 816)
        Renamer.setMinimumSize(QtCore.QSize(545, 520))
        self.verticalLayout_4 = QtGui.QVBoxLayout(Renamer)
        self.verticalLayout_4.setMargin(1)
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.Current_Location_Label = QtGui.QLabel(Renamer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Current_Location_Label.sizePolicy().hasHeightForWidth())
        self.Current_Location_Label.setSizePolicy(sizePolicy)
        self.Current_Location_Label.setMinimumSize(QtCore.QSize(531, 20))
        self.Current_Location_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Current_Location_Label.setWordWrap(True)
        self.Current_Location_Label.setObjectName(_fromUtf8("Current_Location_Label"))
        self.verticalLayout_4.addWidget(self.Current_Location_Label)
        self.splitter = QtGui.QSplitter(Renamer)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.LeftWig = QtGui.QWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LeftWig.sizePolicy().hasHeightForWidth())
        self.LeftWig.setSizePolicy(sizePolicy)
        self.LeftWig.setMinimumSize(QtCore.QSize(191, 420))
        self.LeftWig.setObjectName(_fromUtf8("LeftWig"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.LeftWig)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.CurrLabel = QtGui.QLabel(self.LeftWig)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CurrLabel.sizePolicy().hasHeightForWidth())
        self.CurrLabel.setSizePolicy(sizePolicy)
        self.CurrLabel.setMinimumSize(QtCore.QSize(193, 20))
        self.CurrLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.CurrLabel.setObjectName(_fromUtf8("CurrLabel"))
        self.verticalLayout_3.addWidget(self.CurrLabel)
        self.CurrentView = QtGui.QTableWidget(self.LeftWig)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CurrentView.sizePolicy().hasHeightForWidth())
        self.CurrentView.setSizePolicy(sizePolicy)
        self.CurrentView.setMinimumSize(QtCore.QSize(191, 400))
        self.CurrentView.setObjectName(_fromUtf8("CurrentView"))
        self.CurrentView.setColumnCount(0)
        self.CurrentView.setRowCount(0)
        self.CurrentView.horizontalHeader().setVisible(False)
        self.CurrentView.horizontalHeader().setHighlightSections(True)
        self.CurrentView.horizontalHeader().setStretchLastSection(True)
        self.CurrentView.verticalHeader().setVisible(False)
        self.CurrentView.verticalHeader().setDefaultSectionSize(15)
        self.verticalLayout_3.addWidget(self.CurrentView)
        self.CenterWidg = QtGui.QWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CenterWidg.sizePolicy().hasHeightForWidth())
        self.CenterWidg.setSizePolicy(sizePolicy)
        self.CenterWidg.setMinimumSize(QtCore.QSize(141, 400))
        self.CenterWidg.setObjectName(_fromUtf8("CenterWidg"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.CenterWidg)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.CenterColumn = QtGui.QVBoxLayout()
        self.CenterColumn.setObjectName(_fromUtf8("CenterColumn"))
        spacerItem = QtGui.QSpacerItem(141, 30, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        self.CenterColumn.addItem(spacerItem)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem1 = QtGui.QSpacerItem(30, 23, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.Locate_Button = QtGui.QPushButton(self.CenterWidg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Locate_Button.sizePolicy().hasHeightForWidth())
        self.Locate_Button.setSizePolicy(sizePolicy)
        self.Locate_Button.setMinimumSize(QtCore.QSize(81, 23))
        self.Locate_Button.setMaximumSize(QtCore.QSize(81, 23))
        self.Locate_Button.setObjectName(_fromUtf8("Locate_Button"))
        self.horizontalLayout.addWidget(self.Locate_Button)
        spacerItem2 = QtGui.QSpacerItem(30, 23, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.CenterColumn.addLayout(self.horizontalLayout)
        spacerItem3 = QtGui.QSpacerItem(141, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.CenterColumn.addItem(spacerItem3)
        self.Issue_label = QtGui.QLabel(self.CenterWidg)
        self.Issue_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Issue_label.setObjectName(_fromUtf8("Issue_label"))
        self.CenterColumn.addWidget(self.Issue_label)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.Prefix_lineEdit = QtGui.QLineEdit(self.CenterWidg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Prefix_lineEdit.sizePolicy().hasHeightForWidth())
        self.Prefix_lineEdit.setSizePolicy(sizePolicy)
        self.Prefix_lineEdit.setMinimumSize(QtCore.QSize(121, 20))
        self.Prefix_lineEdit.setMaximumSize(QtCore.QSize(16777215, 20))
        self.Prefix_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.Prefix_lineEdit.setObjectName(_fromUtf8("Prefix_lineEdit"))
        self.horizontalLayout_2.addWidget(self.Prefix_lineEdit)
        self.CenterColumn.addLayout(self.horizontalLayout_2)
        self.DateFormatCoB = QtGui.QComboBox(self.CenterWidg)
        self.DateFormatCoB.setMinimumSize(QtCore.QSize(0, 20))
        self.DateFormatCoB.setMaximumSize(QtCore.QSize(16777215, 20))
        self.DateFormatCoB.setMaxVisibleItems(20)
        self.DateFormatCoB.setObjectName(_fromUtf8("DateFormatCoB"))
        self.CenterColumn.addWidget(self.DateFormatCoB)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.NewName_lineEdit = QtGui.QLineEdit(self.CenterWidg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NewName_lineEdit.sizePolicy().hasHeightForWidth())
        self.NewName_lineEdit.setSizePolicy(sizePolicy)
        self.NewName_lineEdit.setMinimumSize(QtCore.QSize(121, 41))
        self.NewName_lineEdit.setMaximumSize(QtCore.QSize(16777215, 41))
        self.NewName_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.NewName_lineEdit.setObjectName(_fromUtf8("NewName_lineEdit"))
        self.horizontalLayout_3.addWidget(self.NewName_lineEdit)
        self.CenterColumn.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.Suffix_lineEdit = QtGui.QLineEdit(self.CenterWidg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Suffix_lineEdit.sizePolicy().hasHeightForWidth())
        self.Suffix_lineEdit.setSizePolicy(sizePolicy)
        self.Suffix_lineEdit.setMinimumSize(QtCore.QSize(121, 20))
        self.Suffix_lineEdit.setMaximumSize(QtCore.QSize(16777215, 20))
        self.Suffix_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.Suffix_lineEdit.setObjectName(_fromUtf8("Suffix_lineEdit"))
        self.horizontalLayout_4.addWidget(self.Suffix_lineEdit)
        self.CenterColumn.addLayout(self.horizontalLayout_4)
        spacerItem4 = QtGui.QSpacerItem(141, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.CenterColumn.addItem(spacerItem4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem5 = QtGui.QSpacerItem(30, 23, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.Opts_Button = QtGui.QPushButton(self.CenterWidg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Opts_Button.sizePolicy().hasHeightForWidth())
        self.Opts_Button.setSizePolicy(sizePolicy)
        self.Opts_Button.setMinimumSize(QtCore.QSize(81, 0))
        self.Opts_Button.setMaximumSize(QtCore.QSize(81, 23))
        self.Opts_Button.setCheckable(True)
        self.Opts_Button.setObjectName(_fromUtf8("Opts_Button"))
        self.horizontalLayout_5.addWidget(self.Opts_Button)
        spacerItem6 = QtGui.QSpacerItem(30, 23, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.CenterColumn.addLayout(self.horizontalLayout_5)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        spacerItem7 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem7)
        self.OpsBox = QtGui.QGroupBox(self.CenterWidg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OpsBox.sizePolicy().hasHeightForWidth())
        self.OpsBox.setSizePolicy(sizePolicy)
        self.OpsBox.setMinimumSize(QtCore.QSize(140, 90))
        self.OpsBox.setMaximumSize(QtCore.QSize(200, 380))
        self.OpsBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OpsBox.setAlignment(QtCore.Qt.AlignCenter)
        self.OpsBox.setObjectName(_fromUtf8("OpsBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.OpsBox)
        self.gridLayout_2.setMargin(5)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.frame = QtGui.QFrame(self.OpsBox)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frame)
        self.gridLayout_3.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.Pref_CB = QtGui.QCheckBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Pref_CB.sizePolicy().hasHeightForWidth())
        self.Pref_CB.setSizePolicy(sizePolicy)
        self.Pref_CB.setMinimumSize(QtCore.QSize(61, 18))
        self.Pref_CB.setMaximumSize(QtCore.QSize(16777215, 18))
        self.Pref_CB.setObjectName(_fromUtf8("Pref_CB"))
        self.gridLayout_3.addWidget(self.Pref_CB, 0, 0, 1, 1)
        self.Suff_CB = QtGui.QCheckBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Suff_CB.sizePolicy().hasHeightForWidth())
        self.Suff_CB.setSizePolicy(sizePolicy)
        self.Suff_CB.setMinimumSize(QtCore.QSize(61, 18))
        self.Suff_CB.setMaximumSize(QtCore.QSize(16777215, 18))
        self.Suff_CB.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.Suff_CB.setChecked(False)
        self.Suff_CB.setObjectName(_fromUtf8("Suff_CB"))
        self.gridLayout_3.addWidget(self.Suff_CB, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        self.SubSets_Frame = QtGui.QFrame(self.OpsBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubSets_Frame.sizePolicy().hasHeightForWidth())
        self.SubSets_Frame.setSizePolicy(sizePolicy)
        self.SubSets_Frame.setMinimumSize(QtCore.QSize(40, 60))
        self.SubSets_Frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.SubSets_Frame.setFrameShadow(QtGui.QFrame.Plain)
        self.SubSets_Frame.setObjectName(_fromUtf8("SubSets_Frame"))
        self.gridLayout = QtGui.QGridLayout(self.SubSets_Frame)
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.PreNam_RB = QtGui.QRadioButton(self.SubSets_Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PreNam_RB.sizePolicy().hasHeightForWidth())
        self.PreNam_RB.setSizePolicy(sizePolicy)
        self.PreNam_RB.setMinimumSize(QtCore.QSize(16, 20))
        self.PreNam_RB.setMaximumSize(QtCore.QSize(16, 20))
        self.PreNam_RB.setText(_fromUtf8(""))
        self.PreNam_RB.setObjectName(_fromUtf8("PreNam_RB"))
        self.gridLayout.addWidget(self.PreNam_RB, 0, 0, 1, 1)
        self.Nam_Lab = QtGui.QLabel(self.SubSets_Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Nam_Lab.sizePolicy().hasHeightForWidth())
        self.Nam_Lab.setSizePolicy(sizePolicy)
        self.Nam_Lab.setMinimumSize(QtCore.QSize(64, 20))
        self.Nam_Lab.setMaximumSize(QtCore.QSize(16777215, 20))
        self.Nam_Lab.setAlignment(QtCore.Qt.AlignCenter)
        self.Nam_Lab.setObjectName(_fromUtf8("Nam_Lab"))
        self.gridLayout.addWidget(self.Nam_Lab, 0, 1, 1, 1)
        self.SufNam_RB = QtGui.QRadioButton(self.SubSets_Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SufNam_RB.sizePolicy().hasHeightForWidth())
        self.SufNam_RB.setSizePolicy(sizePolicy)
        self.SufNam_RB.setMinimumSize(QtCore.QSize(16, 20))
        self.SufNam_RB.setMaximumSize(QtCore.QSize(16, 20))
        self.SufNam_RB.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.SufNam_RB.setText(_fromUtf8(""))
        self.SufNam_RB.setObjectName(_fromUtf8("SufNam_RB"))
        self.gridLayout.addWidget(self.SufNam_RB, 0, 2, 1, 1)
        self.PreNum_RB = QtGui.QRadioButton(self.SubSets_Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PreNum_RB.sizePolicy().hasHeightForWidth())
        self.PreNum_RB.setSizePolicy(sizePolicy)
        self.PreNum_RB.setMinimumSize(QtCore.QSize(16, 20))
        self.PreNum_RB.setMaximumSize(QtCore.QSize(16, 20))
        self.PreNum_RB.setText(_fromUtf8(""))
        self.PreNum_RB.setObjectName(_fromUtf8("PreNum_RB"))
        self.gridLayout.addWidget(self.PreNum_RB, 1, 0, 1, 1)
        self.Num_Lab = QtGui.QLabel(self.SubSets_Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Num_Lab.sizePolicy().hasHeightForWidth())
        self.Num_Lab.setSizePolicy(sizePolicy)
        self.Num_Lab.setMinimumSize(QtCore.QSize(64, 20))
        self.Num_Lab.setMaximumSize(QtCore.QSize(16777215, 20))
        self.Num_Lab.setAlignment(QtCore.Qt.AlignCenter)
        self.Num_Lab.setObjectName(_fromUtf8("Num_Lab"))
        self.gridLayout.addWidget(self.Num_Lab, 1, 1, 1, 1)
        self.SufNum_RB = QtGui.QRadioButton(self.SubSets_Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SufNum_RB.sizePolicy().hasHeightForWidth())
        self.SufNum_RB.setSizePolicy(sizePolicy)
        self.SufNum_RB.setMinimumSize(QtCore.QSize(16, 20))
        self.SufNum_RB.setMaximumSize(QtCore.QSize(16, 20))
        self.SufNum_RB.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.SufNum_RB.setText(_fromUtf8(""))
        self.SufNum_RB.setObjectName(_fromUtf8("SufNum_RB"))
        self.gridLayout.addWidget(self.SufNum_RB, 1, 2, 1, 1)
        self.PreAlp_RB = QtGui.QRadioButton(self.SubSets_Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PreAlp_RB.sizePolicy().hasHeightForWidth())
        self.PreAlp_RB.setSizePolicy(sizePolicy)
        self.PreAlp_RB.setMinimumSize(QtCore.QSize(16, 20))
        self.PreAlp_RB.setMaximumSize(QtCore.QSize(16, 20))
        self.PreAlp_RB.setText(_fromUtf8(""))
        self.PreAlp_RB.setObjectName(_fromUtf8("PreAlp_RB"))
        self.gridLayout.addWidget(self.PreAlp_RB, 2, 0, 1, 1)
        self.Alp_Lab = QtGui.QLabel(self.SubSets_Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Alp_Lab.sizePolicy().hasHeightForWidth())
        self.Alp_Lab.setSizePolicy(sizePolicy)
        self.Alp_Lab.setMinimumSize(QtCore.QSize(64, 20))
        self.Alp_Lab.setMaximumSize(QtCore.QSize(16777215, 20))
        self.Alp_Lab.setAlignment(QtCore.Qt.AlignCenter)
        self.Alp_Lab.setObjectName(_fromUtf8("Alp_Lab"))
        self.gridLayout.addWidget(self.Alp_Lab, 2, 1, 1, 1)
        self.SufAlp_RB = QtGui.QRadioButton(self.SubSets_Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SufAlp_RB.sizePolicy().hasHeightForWidth())
        self.SufAlp_RB.setSizePolicy(sizePolicy)
        self.SufAlp_RB.setMinimumSize(QtCore.QSize(16, 20))
        self.SufAlp_RB.setMaximumSize(QtCore.QSize(16, 20))
        self.SufAlp_RB.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.SufAlp_RB.setText(_fromUtf8(""))
        self.SufAlp_RB.setObjectName(_fromUtf8("SufAlp_RB"))
        self.gridLayout.addWidget(self.SufAlp_RB, 2, 2, 1, 1)
        self.gridLayout_2.addWidget(self.SubSets_Frame, 1, 0, 1, 1)
        self.AlphaFrame = QtGui.QFrame(self.OpsBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AlphaFrame.sizePolicy().hasHeightForWidth())
        self.AlphaFrame.setSizePolicy(sizePolicy)
        self.AlphaFrame.setMinimumSize(QtCore.QSize(125, 90))
        self.AlphaFrame.setMaximumSize(QtCore.QSize(190, 16777215))
        self.AlphaFrame.setFrameShape(QtGui.QFrame.Box)
        self.AlphaFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.AlphaFrame.setObjectName(_fromUtf8("AlphaFrame"))
        self.gridLayout_4 = QtGui.QGridLayout(self.AlphaFrame)
        self.gridLayout_4.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.gridLayout_4.setMargin(5)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem8)
        self.More_frame = QtGui.QFrame(self.AlphaFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.More_frame.sizePolicy().hasHeightForWidth())
        self.More_frame.setSizePolicy(sizePolicy)
        self.More_frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.More_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.More_frame.setObjectName(_fromUtf8("More_frame"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.More_frame)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_3 = QtGui.QLabel(self.More_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(91, 21))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 21))
        self.label_3.setTextFormat(QtCore.Qt.PlainText)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_6.addWidget(self.label_3)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(3)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem9 = QtGui.QSpacerItem(40, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem9)
        self.PreAddDig_SB = QtGui.QSpinBox(self.More_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PreAddDig_SB.sizePolicy().hasHeightForWidth())
        self.PreAddDig_SB.setSizePolicy(sizePolicy)
        self.PreAddDig_SB.setMinimumSize(QtCore.QSize(25, 21))
        self.PreAddDig_SB.setMaximumSize(QtCore.QSize(25, 21))
        self.PreAddDig_SB.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PreAddDig_SB.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.PreAddDig_SB.setMaximum(30)
        self.PreAddDig_SB.setProperty("value", 0)
        self.PreAddDig_SB.setObjectName(_fromUtf8("PreAddDig_SB"))
        self.horizontalLayout_6.addWidget(self.PreAddDig_SB)
        self.AddDig_SB = QtGui.QSpinBox(self.More_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddDig_SB.sizePolicy().hasHeightForWidth())
        self.AddDig_SB.setSizePolicy(sizePolicy)
        self.AddDig_SB.setMinimumSize(QtCore.QSize(31, 21))
        self.AddDig_SB.setMaximumSize(QtCore.QSize(31, 21))
        self.AddDig_SB.setFrame(True)
        self.AddDig_SB.setAlignment(QtCore.Qt.AlignCenter)
        self.AddDig_SB.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.AddDig_SB.setMaximum(30)
        self.AddDig_SB.setObjectName(_fromUtf8("AddDig_SB"))
        self.horizontalLayout_6.addWidget(self.AddDig_SB)
        self.SufAddDig_SB = QtGui.QSpinBox(self.More_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SufAddDig_SB.sizePolicy().hasHeightForWidth())
        self.SufAddDig_SB.setSizePolicy(sizePolicy)
        self.SufAddDig_SB.setMinimumSize(QtCore.QSize(25, 21))
        self.SufAddDig_SB.setMaximumSize(QtCore.QSize(25, 21))
        self.SufAddDig_SB.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.SufAddDig_SB.setMaximum(30)
        self.SufAddDig_SB.setObjectName(_fromUtf8("SufAddDig_SB"))
        self.horizontalLayout_6.addWidget(self.SufAddDig_SB)
        spacerItem10 = QtGui.QSpacerItem(40, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem10)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.label_4 = QtGui.QLabel(self.More_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(91, 21))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 21))
        self.label_4.setTextFormat(QtCore.Qt.PlainText)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_6.addWidget(self.label_4)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(3)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        spacerItem11 = QtGui.QSpacerItem(40, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem11)
        self.PreStart_SB = QtGui.QSpinBox(self.More_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PreStart_SB.sizePolicy().hasHeightForWidth())
        self.PreStart_SB.setSizePolicy(sizePolicy)
        self.PreStart_SB.setMinimumSize(QtCore.QSize(25, 21))
        self.PreStart_SB.setMaximumSize(QtCore.QSize(25, 21))
        self.PreStart_SB.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PreStart_SB.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.PreStart_SB.setMinimum(0)
        self.PreStart_SB.setMaximum(999999999)
        self.PreStart_SB.setProperty("value", 1)
        self.PreStart_SB.setObjectName(_fromUtf8("PreStart_SB"))
        self.horizontalLayout_11.addWidget(self.PreStart_SB)
        self.NumStart_SB = QtGui.QSpinBox(self.More_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NumStart_SB.sizePolicy().hasHeightForWidth())
        self.NumStart_SB.setSizePolicy(sizePolicy)
        self.NumStart_SB.setMinimumSize(QtCore.QSize(31, 21))
        self.NumStart_SB.setMaximumSize(QtCore.QSize(31, 21))
        self.NumStart_SB.setFrame(True)
        self.NumStart_SB.setAlignment(QtCore.Qt.AlignCenter)
        self.NumStart_SB.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.NumStart_SB.setMinimum(0)
        self.NumStart_SB.setMaximum(999999999)
        self.NumStart_SB.setProperty("value", 1)
        self.NumStart_SB.setObjectName(_fromUtf8("NumStart_SB"))
        self.horizontalLayout_11.addWidget(self.NumStart_SB)
        self.SufStart_SB = QtGui.QSpinBox(self.More_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SufStart_SB.sizePolicy().hasHeightForWidth())
        self.SufStart_SB.setSizePolicy(sizePolicy)
        self.SufStart_SB.setMinimumSize(QtCore.QSize(25, 21))
        self.SufStart_SB.setMaximumSize(QtCore.QSize(25, 21))
        self.SufStart_SB.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.SufStart_SB.setMinimum(0)
        self.SufStart_SB.setMaximum(999999999)
        self.SufStart_SB.setProperty("value", 1)
        self.SufStart_SB.setObjectName(_fromUtf8("SufStart_SB"))
        self.horizontalLayout_11.addWidget(self.SufStart_SB)
        spacerItem12 = QtGui.QSpacerItem(40, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem12)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        self.label_5 = QtGui.QLabel(self.More_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(91, 21))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 21))
        self.label_5.setTextFormat(QtCore.Qt.PlainText)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_6.addWidget(self.label_5)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(-1, -1, -1, 3)
        self.horizontalLayout_12.setSpacing(3)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        spacerItem13 = QtGui.QSpacerItem(40, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem13)
        self.PreSep_lineEdit = QtGui.QLineEdit(self.More_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PreSep_lineEdit.sizePolicy().hasHeightForWidth())
        self.PreSep_lineEdit.setSizePolicy(sizePolicy)
        self.PreSep_lineEdit.setMinimumSize(QtCore.QSize(25, 21))
        self.PreSep_lineEdit.setMaximumSize(QtCore.QSize(25, 21))
        self.PreSep_lineEdit.setMaxLength(1)
        self.PreSep_lineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PreSep_lineEdit.setObjectName(_fromUtf8("PreSep_lineEdit"))
        self.horizontalLayout_12.addWidget(self.PreSep_lineEdit)
        self.NumSep_lineEdit = QtGui.QLineEdit(self.More_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NumSep_lineEdit.sizePolicy().hasHeightForWidth())
        self.NumSep_lineEdit.setSizePolicy(sizePolicy)
        self.NumSep_lineEdit.setMinimumSize(QtCore.QSize(30, 21))
        self.NumSep_lineEdit.setMaximumSize(QtCore.QSize(30, 21))
        self.NumSep_lineEdit.setText(_fromUtf8(""))
        self.NumSep_lineEdit.setMaxLength(1)
        self.NumSep_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.NumSep_lineEdit.setObjectName(_fromUtf8("NumSep_lineEdit"))
        self.horizontalLayout_12.addWidget(self.NumSep_lineEdit)
        self.SufSep_lineEdit = QtGui.QLineEdit(self.More_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SufSep_lineEdit.sizePolicy().hasHeightForWidth())
        self.SufSep_lineEdit.setSizePolicy(sizePolicy)
        self.SufSep_lineEdit.setMinimumSize(QtCore.QSize(25, 21))
        self.SufSep_lineEdit.setMaximumSize(QtCore.QSize(25, 21))
        self.SufSep_lineEdit.setMaxLength(1)
        self.SufSep_lineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.SufSep_lineEdit.setObjectName(_fromUtf8("SufSep_lineEdit"))
        self.horizontalLayout_12.addWidget(self.SufSep_lineEdit)
        spacerItem14 = QtGui.QSpacerItem(40, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem14)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)
        self.Time_Sep_line = QtGui.QFrame(self.More_frame)
        self.Time_Sep_line.setFrameShape(QtGui.QFrame.HLine)
        self.Time_Sep_line.setFrameShadow(QtGui.QFrame.Sunken)
        self.Time_Sep_line.setObjectName(_fromUtf8("Time_Sep_line"))
        self.verticalLayout_6.addWidget(self.Time_Sep_line)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.MilliSec_CB = QtGui.QCheckBox(self.More_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MilliSec_CB.sizePolicy().hasHeightForWidth())
        self.MilliSec_CB.setSizePolicy(sizePolicy)
        self.MilliSec_CB.setMinimumSize(QtCore.QSize(82, 18))
        self.MilliSec_CB.setMaximumSize(QtCore.QSize(16777215, 18))
        self.MilliSec_CB.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.MilliSec_CB.setObjectName(_fromUtf8("MilliSec_CB"))
        self.horizontalLayout_13.addWidget(self.MilliSec_CB)
        self.HrForm_CB = QtGui.QCheckBox(self.More_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HrForm_CB.sizePolicy().hasHeightForWidth())
        self.HrForm_CB.setSizePolicy(sizePolicy)
        self.HrForm_CB.setMinimumSize(QtCore.QSize(62, 18))
        self.HrForm_CB.setMaximumSize(QtCore.QSize(16777215, 18))
        self.HrForm_CB.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.HrForm_CB.setObjectName(_fromUtf8("HrForm_CB"))
        self.horizontalLayout_13.addWidget(self.HrForm_CB)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_10.addWidget(self.More_frame)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem15)
        self.gridLayout_4.addLayout(self.horizontalLayout_10, 3, 0, 1, 1)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem16)
        self.AlphaNum_CB = QtGui.QCheckBox(self.AlphaFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AlphaNum_CB.sizePolicy().hasHeightForWidth())
        self.AlphaNum_CB.setSizePolicy(sizePolicy)
        self.AlphaNum_CB.setMinimumSize(QtCore.QSize(90, 40))
        self.AlphaNum_CB.setMaximumSize(QtCore.QSize(110, 40))
        self.AlphaNum_CB.setObjectName(_fromUtf8("AlphaNum_CB"))
        self.horizontalLayout_14.addWidget(self.AlphaNum_CB)
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem17)
        self.gridLayout_4.addLayout(self.horizontalLayout_14, 0, 0, 1, 1)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem18)
        self.NameDate_CB = QtGui.QCheckBox(self.AlphaFrame)
        self.NameDate_CB.setMinimumSize(QtCore.QSize(90, 20))
        self.NameDate_CB.setMaximumSize(QtCore.QSize(110, 20))
        self.NameDate_CB.setObjectName(_fromUtf8("NameDate_CB"))
        self.horizontalLayout_15.addWidget(self.NameDate_CB)
        spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem19)
        self.gridLayout_4.addLayout(self.horizontalLayout_15, 1, 0, 1, 1)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        spacerItem20 = QtGui.QSpacerItem(40, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem20)
        self.More_Button = QtGui.QPushButton(self.AlphaFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.More_Button.sizePolicy().hasHeightForWidth())
        self.More_Button.setSizePolicy(sizePolicy)
        self.More_Button.setMaximumSize(QtCore.QSize(110, 20))
        self.More_Button.setCheckable(True)
        self.More_Button.setObjectName(_fromUtf8("More_Button"))
        self.horizontalLayout_16.addWidget(self.More_Button)
        spacerItem21 = QtGui.QSpacerItem(40, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem21)
        self.gridLayout_4.addLayout(self.horizontalLayout_16, 2, 0, 1, 1)
        spacerItem22 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        self.gridLayout_4.addItem(spacerItem22, 4, 0, 1, 1)
        self.gridLayout_2.addWidget(self.AlphaFrame, 2, 0, 1, 1)
        spacerItem23 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        self.gridLayout_2.addItem(spacerItem23, 3, 0, 1, 1)
        self.horizontalLayout_9.addWidget(self.OpsBox)
        spacerItem24 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem24)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        spacerItem25 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem25)
        self.CenterColumn.addLayout(self.verticalLayout_5)
        spacerItem26 = QtGui.QSpacerItem(141, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        self.CenterColumn.addItem(spacerItem26)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        spacerItem27 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem27)
        self.Rename_Button = QtGui.QPushButton(self.CenterWidg)
        self.Rename_Button.setMinimumSize(QtCore.QSize(101, 51))
        self.Rename_Button.setObjectName(_fromUtf8("Rename_Button"))
        self.horizontalLayout_7.addWidget(self.Rename_Button)
        spacerItem28 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem28)
        self.CenterColumn.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8.addLayout(self.CenterColumn)
        self.RightWig = QtGui.QWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RightWig.sizePolicy().hasHeightForWidth())
        self.RightWig.setSizePolicy(sizePolicy)
        self.RightWig.setMinimumSize(QtCore.QSize(191, 420))
        self.RightWig.setObjectName(_fromUtf8("RightWig"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.RightWig)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.PrevLabel = QtGui.QLabel(self.RightWig)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PrevLabel.sizePolicy().hasHeightForWidth())
        self.PrevLabel.setSizePolicy(sizePolicy)
        self.PrevLabel.setMinimumSize(QtCore.QSize(191, 20))
        self.PrevLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.PrevLabel.setObjectName(_fromUtf8("PrevLabel"))
        self.verticalLayout_2.addWidget(self.PrevLabel)
        self.PreView = QtGui.QTableWidget(self.RightWig)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PreView.sizePolicy().hasHeightForWidth())
        self.PreView.setSizePolicy(sizePolicy)
        self.PreView.setMinimumSize(QtCore.QSize(191, 400))
        self.PreView.setObjectName(_fromUtf8("PreView"))
        self.PreView.setColumnCount(0)
        self.PreView.setRowCount(0)
        self.PreView.horizontalHeader().setVisible(False)
        self.PreView.horizontalHeader().setStretchLastSection(True)
        self.PreView.verticalHeader().setVisible(False)
        self.PreView.verticalHeader().setDefaultSectionSize(15)
        self.verticalLayout_2.addWidget(self.PreView)
        self.verticalLayout_4.addWidget(self.splitter)

        self.retranslateUi(Renamer)
        QtCore.QMetaObject.connectSlotsByName(Renamer)

    def retranslateUi(self, Renamer):
        Renamer.setWindowTitle(_translate("Renamer", "Bulk Renamer", None))
        self.Current_Location_Label.setText(_translate("Renamer", "Bulk File Renamer", None))
        self.CurrLabel.setText(_translate("Renamer", "Current", None))
        self.Locate_Button.setText(_translate("Renamer", "Folder", None))
        self.Issue_label.setText(_translate("Renamer", "TextLabel", None))
        self.Prefix_lineEdit.setPlaceholderText(_translate("Renamer", "Prefix", None))
        self.NewName_lineEdit.setPlaceholderText(_translate("Renamer", "New Name goes here", None))
        self.Suffix_lineEdit.setPlaceholderText(_translate("Renamer", "Suffix", None))
        self.Opts_Button.setText(_translate("Renamer", "Options", None))
        self.OpsBox.setTitle(_translate("Renamer", "Options", None))
        self.Pref_CB.setText(_translate("Renamer", "Prefix", None))
        self.Suff_CB.setText(_translate("Renamer", "Suffix", None))
        self.PreNam_RB.setToolTip(_translate("Renamer", "Named", None))
        self.Nam_Lab.setText(_translate("Renamer", "Named", None))
        self.SufNam_RB.setToolTip(_translate("Renamer", "Named", None))
        self.PreNum_RB.setToolTip(_translate("Renamer", "Numbered", None))
        self.Num_Lab.setText(_translate("Renamer", "Numbered", None))
        self.SufNum_RB.setToolTip(_translate("Renamer", "Numbered", None))
        self.PreAlp_RB.setToolTip(_translate("Renamer", "Alphanumeric", None))
        self.Alp_Lab.setText(_translate("Renamer", "Alphanumeric", None))
        self.SufAlp_RB.setToolTip(_translate("Renamer", "Alphanumeric", None))
        self.label_3.setText(_translate("Renamer", "Additional Digits:", None))
        self.PreAddDig_SB.setToolTip(_translate("Renamer", "Addtional Prefix digits", None))
        self.SufAddDig_SB.setToolTip(_translate("Renamer", "Addtional Suffix digits", None))
        self.label_4.setText(_translate("Renamer", "Starting Value:", None))
        self.PreStart_SB.setToolTip(_translate("Renamer", "Starting Prefix value", None))
        self.SufStart_SB.setToolTip(_translate("Renamer", "Starting suffix value", None))
        self.label_5.setText(_translate("Renamer", "Seperating Character:", None))
        self.PreSep_lineEdit.setText(_translate("Renamer", "_", None))
        self.SufSep_lineEdit.setText(_translate("Renamer", "_", None))
        self.MilliSec_CB.setToolTip(_translate("Renamer", "Adds milliseconds to the date (if possible)", None))
        self.MilliSec_CB.setText(_translate("Renamer", "msec", None))
        self.HrForm_CB.setText(_translate("Renamer", "24 hour", None))
        self.AlphaNum_CB.setText(_translate("Renamer", "Alphanumeric\n"
"Numbering", None))
        self.NameDate_CB.setToolTip(_translate("Renamer", "Rename the files by their date.", None))
        self.NameDate_CB.setText(_translate("Renamer", "Name by Date", None))
        self.More_Button.setText(_translate("Renamer", "More", None))
        self.Rename_Button.setText(_translate("Renamer", "Rename", None))
        self.PrevLabel.setText(_translate("Renamer", "Preview", None))

